### ISSUE TITLE
Errors for KeyCode3.js and KeyCode4.js

### ISSUE THREAD

**Issue by ReactGirl** [elijahmanor/egghead-lesson-16.7-hooks-convert-class-to-function#2]
×
←→1 of 2 errors on the page
TypeError: Object(...) is not a function
KeyCode
src/KeyCode3.js:4
  1 | import React, { Fragment, useState, useEffect } from "react";
  2 | import KeyCodeBlock from "./KeyCodeBlock";
  3 | 
> 4 | export default function KeyCode() {
  5 |   const [{ keyCode, key, code }, setCodes] = useState({});
  6 | 
  7 |   useEffect(() => {

**Comment by elijahmanor** [comment]
Hmm... so you cloned this repo, installed node_modules, and started the web app?

```
git clone git@github.com:elijahmanor/egghead-lesson-16.7-hooks-convert-class-to-function.git
cd egghead-lesson-16.7-hooks-convert-class-to-function
cd react-hooks
npm install
npm start
```

Are you seeing the error in the browser that comes up after the above?

**Comment by elijahmanor** [comment]
So sorry, it turns out my local deps were wrong in package.json. I was using different node_modules than was pushed up. I pushed a change and now it works. Please try again. Thanks for letting me know

**Comment by elijahmanor** [comment]
This should resolve your issue. If not please feel free to open up another issue. I'm going to close this for now.
